### ISSUE TITLE
Basic admin panel

### ISSUE THREAD

**Issue by Faustvii** [Faustvii/beth-leaderboard#18]
- Should be able to revert a match in case it was registered incorrectly
  - Only if the players in the match haven't played any matches since. (No newer matches)

Other things?

**Comment by Faustvii** [comment]
It should also be possible to add / change seasons

**Comment by Kechr** [comment]
> Only if the players in the match haven't played any matches since. (No newer matches)

This is irrelevant now, right?

We could add 'add game' functionality now also, if someone forgets to log a match

**Comment by Faustvii** [comment]
> > Only if the players in the match haven't played any matches since. (No newer matches)
> 
> This is irrelevant now, right?
> 
> We could add 'add game' functionality now also, if someone forgets to log a match
It is still relevant, since their elo would have been used in a newer match, meaning they "new" match would have been calculated based on a "wrong" elo.
Example
Player A 1500 elo
Player B 1500 elo
They incorrectly log Player A won against B and their elo changed by 16
Now player A(1516) and player C(1500) play a match and player A loses and their elo changes by 18
If we remove Player A vs B match, we would "technically" get a elo back no problem but player A would have lost 2 elo more than they should in this example and C would have gained 2 more than they should.

**Comment by Srensommer** [comment]
Since elo is calculated when it is queried this is no longer a concern right?
Removing any match registered at anytime will result in correct elo anyhow cause' it would be recalculated.
