### ISSUE TITLE
Historic data (Older seasons)

### ISSUE THREAD

**Issue by Faustvii** [Faustvii/beth-leaderboard#25]
- It should be possible to view the leaderboard for a different season.
- Stats and personal stats should also be based on season (They currently aren't)
  - It might be interesting to keep a global stats across all seasons as well.

**Comment by Srensommer** [comment]
This is me
I work on this

**Comment by Faustvii** [comment]
Look into the possibility of an Elysia middleware so every method has access to the active season from the context instead of us potentially querying it multiple times and we can potentially make it part of the route..

**Comment by djonn** [comment]
Implemented in #66
