### ISSUE TITLE
BUG: Different elo points in "Latest games" and profile

### ISSUE THREAD

**Issue by jns-poly** [Faustvii/beth-leaderboard#38]
Morten Lyng had his first game today and won. On his profile it says he has 1 game and the elo change tracker shows he won 13 points, But looking at the lastest games in /stats it says he won 15 points. The leaderboard confirms that he won 13 points.

**Comment by Srensommer** [comment]
🤷‍♂️

**Comment by Srensommer** [comment]
spurgt
