### ISSUE TITLE
Add 'Start new season' functionality to admin

### ISSUE THREAD

**Issue by Kechr** [Faustvii/beth-leaderboard#55]
Admins should be able to start a new season from the admin page.

The admin should be able to
  - [x] Create a new season
  - [x] Edit an existing season
  - [x] Delete an existing season

**Comment by Faustvii** [comment]
Sounds like we have two places we would like a  `date` component of some kind.
- Creating/editing seasons
- Editing matches

**Comment by Kechr** [comment]
@Faustvii The native datetime picker seems good enough IMO 
![image](https://github.com/Faustvii/beth-leaderboard/assets/55458479/1e0f619d-849c-471c-a722-2aff6d99a361)
